# Generated by Django 2.1.5 on 2019-04-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
